### ISSUE TITLE
a question about Lanenet

### ISSUE THREAD

**Issue by hellosher** [zacario-li/libtorch_cpp_mobilenetv2_5classes#1]
@zacario-li  Sorry to bother you. Could you please share your whole code code using mobileNetV2 as the enconder phase on GitHub? Thank you very much?

**Comment by zacario-li** [comment]
@hellosher Hi, sorry for it, I can't give you the code. But another code you can refer, that code use ENet as backbone, and it has very good performance.
[enet-lanenet](https://github.com/stesha2016/lanenet-enet-hnet)
