### ISSUE TITLE
mobilenetv2 pytorch version

### ISSUE THREAD

**Issue by defenceVT** [zacario-li/libtorch_cpp_mobilenetv2_5classes#2]
hi, i what to know which version of the mobilenetv2 you traced for this  "libtorch_cpp_mobilenetv2_5classes"?

**Comment by zacario-li** [comment]
mobilenet_v2_1.0_224

**Comment by switch626** [comment]
Hello, great work you done. I wonder to know how to generate the *.pt model use python. I try to get the yoloV3 model use tracing method, but lots errors appears. So I want to learn how to trace the model with you. :) Thank you.

**Comment by zacario-li** [comment]
> Hello, great work you done. I wonder to know how to generate the *.pt model use python. I try to get the yoloV3 model use tracing method, but lots errors appears. So I want to learn how to trace the model with you. :) Thank you.

I just use torch.jit.trace method to create the *.pt file.

**Comment by switch626** [comment]
ok, thanks a lot. So do you mind to answer one more question? Do you think it's feasible to generate a yolo v3 model through torch.jit.trace method? I am looking forward to your reply.

**Comment by zacario-li** [comment]
> ok, thanks a lot. So do you mind to answer one more question? Do you think it's feasible to generate a yolo v3 model through torch.jit.trace method? I am looking forward to your reply.

If you can run the model in pytorch, I think it will no problem in jit.trace.

**Comment by switch626** [comment]
OK! got it!
